# Generated by Django 5.1.4 on 2024-12-13 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('title', 'user')},
        ),
    ]
