# Generated by Django 5.1.4 on 2024-12-11 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=125),
            preserve_default=False,
        ),
    ]
