# Generated by Django 5.1.4 on 2025-03-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_date'),
        ('wallet', '0003_wallet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='wallet.wallet'),
        ),
    ]
