# Generated by Django 5.1.4 on 2025-03-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_date'),
        ('wallet', '0003_wallet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.wallet'),
        ),
    ]
