# Generated by Django 5.1.4 on 2025-03-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_income_wallet'),
        ('wallet', '0003_wallet_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='wallet.wallet'),
        ),
    ]
